config/routes.rb
Rails.application.routes.draw do
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #一覧画面に対応するアクション
    def index
        #userクラスのデータを全て持ってくる
        @users = User.all
    end
    #新規作成画面に対応するアクション
    def new
        @user = User.new
    end

    #新規登録するためのアクション
    def create
        User.create(user_params)
    end

    def edit
        @user = User.find(params[:id])
    end

    #更新を行うためのアクション
    def update
        user = User.find(params[:id])
        user.update(user_params)
    end

    #削除をするためのアクション
    def destroy
        user = User.find(params[:id])
        user.destroy
    end

    private
    def user_params
        #データベースに登録する変数を制限する
        params.require(:user).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", users_path %>

app/views/users/destroy.html.erb
<h1>削除完了</h1>
<%= link_to "一覧画面へ", "/users" %>

app/views/users/edit.html.erb
<p>更新</p>
<%= form_with model: @user, local: true do |f| %>
  <p><%= f.text_field :name %></p>
  <p><%= f.text_field :age %></p>
  <%= f.submit "送信" %>
<% end %>

app/views/users/index.html.erb
<%= link_to "投稿画面へ", new_user_path %>
<% @users.each do |user| %>
    <p>
        <%= user.name %>
        <%= user.age %>
        <%= link_to "編集", edit_user_path(user), method: :get %>
        <%= link_to "削除", user_path(user), method: :delete, data: {confirm: "削除しますか？"} %>
    </p>
<% end %>

app/views/users/new.html.erb
<p>新規投稿</p>
<%= form_with model: @user, url: "/users", method: :post, local: true do |f| %>
    <p>お名前:<%= f.text_field :name %></p>
    <p>年齢:<%= f.text_field :age %></p>
    <%= f.submit "送信" %>
<% end %>

app/views/users/update.html.erb
<h1>更新完了</h1>
<%= link_to "一覧画面へ", users_path %>